services:
  minio:
    image: minio/minio
    command: server --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - minio-data:/mnt/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    env_file:
      - .env
    ports:
      - 4000:4000
    restart: always
    hostname: web
    depends_on:
      - minio

volumes:
  minio-data:
